export { createDatabase, saveDatabase, type Database } from './db'
export { createNote, getNote, getAllNotes, deleteNote, type Note } from './notes'
export { generateEmbedding, cosineSimilarity } from './embeddings'
export { indexNote, searchNotes, type SearchResult } from './search'
export { clusterNotes, getClusters, type Cluster } from './clustering'
export const VERSION = '0.0.1'
